## Exercici 1


In [11]:
import numpy as np
from numpy import random

def resum_estadistic(a):
    if a.ndim == 1:
        media = np.mean(a)
        mediana =np.median(a)
        varianza = np.var(a)
        rang = np.ptp(a)
        minim = np.amin(a)
        perc25 = np.percentile(a,25)
        perc50 = np.percentile(a,50)
        perc75 = np.percentile(a,75)
        maxim = np.amax(a)  
        print('Mitjana:', media,'\nMediana:', mediana, '\nVariança:', varianza,'\nRang:', rang, '\nMínim:', minim,
             '\nPer 25%:', perc25, '\nPer 50%:',perc50, '\nPerc 75%:', perc75,'\nMàxim:',maxim)
        print(a)
    else:   
        print("Error. L'array només pot tenir una dimensió")
        

arr0 = np.array(8)
arr1 = np.array([1,2,3,4,5,6])
arr1a = random.randint(100, size=(20))
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

resum_estadistic(arr1)


Mitjana: 3.5 
Mediana: 3.5 
Variança: 2.9166666666666665 
Rang: 5 
Mínim: 1 
Per 25%: 2.25 
Per 50%: 3.5 
Perc 75%: 4.75 
Màxim: 6
[1 2 3 4 5 6]


## Exercici 2


In [12]:
def aleatoris(n):
    return random.randint(100,size=(n,n))
                          
n = 4
#n = 10
print(aleatoris(n))   

[[12 85 49 30]
 [43 23 33 57]
 [ 7 19 67 99]
 [ 4 24 86 49]]


## Exercici 3

In [13]:
def totals(a):
    sum_files = np.sum(a, axis=1)
    sum_col = np.sum(a, axis=0)
    print('La matriu és:\n',a)
    print('Els totals per fila són:', sum_files)
    print('Els totals per columna són', sum_col)
   
n=4
m=3
a =random.randint(10,size=(n,m))

totals(a)  

La matriu és:
 [[3 6 4]
 [0 6 7]
 [8 2 9]
 [0 2 8]]
Els totals per fila són: [13 13 19 10]
Els totals per columna són [11 16 28]


## Exercici 4

In [9]:
import numpy as np

a1 = np.array([2, 4, 8, 1,1])
a2 = np.array([1, 3, 3, 5,8])


def correl(a1,a2):
    numerador = np.sum((a1-np.mean(a1)) * (a2-np.mean(a2)))  
    denominador = np.sqrt((np.sum((a1-np.mean(a1))**2)) * (np.sum((a2-np.mean(a2))**2)))
    c_corr = numerador/denominador
    return c_corr

correl(a1,a2)

-0.4164613615708485

In [10]:
np.corrcoef(a1,a2)

array([[ 1.        , -0.41646136],
       [-0.41646136,  1.        ]])